apiVersion: apps/v1
kind: Deployment
metadata:
  name: validating-webhook
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Deploy after pod is running
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: webhook
        image: flowdopip/validating-webhook:latest
        ports:
        - containerPort: 8443
        volumeMounts:
          - name: webhook-certs
            mountPath: "/etc/webhook/certs"
            readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: webhook-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: validating-webhook-service
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # Deploy after pod is running
spec:
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: https-webhook
  selector:
    app: web
  type: ClusterIP
