apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pod-label-validation
  annotations:
    argocd.argoproj.io/sync-wave: "4"  # Deploy after pod is running
webhooks:
  - name: pod-label-validator.default.svc
    rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      operations: ["CREATE", "UPDATE"]
      resources: ["pods"]
      scope:       "Namespaced"
    failurePolicy: Fail
    sideEffects: None
    clientConfig:
      service:
        name: validating-webhook-service
        namespace: default
        path: "/validate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURyakNDQXBhZ0F3SUJBZ0lVU1ZwVG5LNGJQZ25oVEFXUXMyemJ4ZkNxazRRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd01URXZNQzBHQTFVRUF3d21kbUZzYVdSaGRHbHVaeTEzWldKb2IyOXJMWE5sY25acFkyVXVaR1ZtWVhWcwpkQzV6ZG1Nd0hoY05NalV3TVRJM01URTFPVEkwV2hjTk1qWXdNVEkzTVRFMU9USTBXakF4TVM4d0xRWURWUVFECkRDWjJZV3hwWkdGMGFXNW5MWGRsWW1odmIyc3RjMlZ5ZG1salpTNWtaV1poZFd4MExuTjJZekNDQVNJd0RRWUoKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTkZLT2RFWXRUcktERTF1azVCdHRyTC9WSllsSnQ3NwpsS2hmM3ZJQkEvNmdKdStJaGRQellPaWNrdmlYaEdMVnFQWGh5VmM5N3ZkTFpKNVVQZHYvWkJ2SHVzQktOM0VzCis2YnBGcWRxRnM2Ty9TeTgwSVYrN3RNT3lCZDg4bmt0Tlh4TDRjRlRxdkcvVmQ1U005RHlMd2xvc2Y1eDVVK24KT1UwK1l2ZGUvWEVuTEQ1SllramJrSWd5YlpELzlhZmlqZUhKOXJxMU5zVVNlcWdWTENRVDg1UjRNeTdiTmVnZgp1TWtuUHhKUUtKOC9SMjBlSXV5R3RjOXdTei9DT2pPMGlPMkdFQXk4US9vM2FMMjQrOTJ1TWJZZmRPNUxHSnJBCjF1c21vTTdHUFdWcGVjcWpPNm9lbGJJRTNjem1RNnFxbC8xWHpTRFZVWHVtOW5WckU1QW44RmtDQXdFQUFhT0IKdlRDQnVqQWRCZ05WSFE0RUZnUVVvQlczY2Q0WEhKZ2lHbzU0ekJhZ1d2cTEwaDB3SHdZRFZSMGpCQmd3Rm9BVQpvQlczY2Q0WEhKZ2lHbzU0ekJhZ1d2cTEwaDB3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekJuQmdOVkhSRUVZREJlCmdpWjJZV3hwWkdGMGFXNW5MWGRsWW1odmIyc3RjMlZ5ZG1salpTNWtaV1poZFd4MExuTjJZNEkwZG1Gc2FXUmgKZEdsdVp5MTNaV0pvYjI5ckxYTmxjblpwWTJVdVpHVm1ZWFZzZEM1emRtTXVZMngxYzNSbGNpNXNiMk5oYkRBTgpCZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFrQUZJUlFYNXdLT3lkeVlqREV0Q2JVSjJZVTBWVlRSVVJERmZCTFUzClpzMmp0QnhhTzZ4U2VrYVl0K1ZjQ2pCNjhwNE8xaXR5cGtkQnltN1FpRHRFMm00VUtCemVmU2gySEU5RTVmVFIKUXRyWjVVTXA1S0I3NDQzeEt1QThVVm9mUW5lamo3aWJkVG1nRzg4QlRhOGo0NC8rMnhMeDBYeW1WcUN3SE93dQpXNlVHN2QvRU14SmlJVjZtUXE4aUVlYlVPZjc1dUZZS3FyVkJjWnk0M0hTcVBjdHlISDZROEZvWlhaR2ZFWksvCmhmdUNndzVxdnVjMyttejhRMjRLQWJmZmdoZURob2Y4VXRQZGpGVWtXM2h4Vk5qd250R0k5L1hiOG9YYXBVT0IKR25LNTFQT1lnajVnMDJMM1BjL00xQlM3cmEzOXhMbzJQUERhU1J2SkNxNU1nUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
