apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-cert
  annotations:
    argocd.argoproj.io/sync-wave: "4"  # Deploy after pod is running
    # cert-manager.io/inject-ca-from: default/validating-webhook-cert
webhooks:
  - name: validating-webhook-service.default.svc
    rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      operations: ["CREATE", "UPDATE"]
      resources: ["pods"]
      scope:       "Namespaced"
    failurePolicy: Fail
    sideEffects: None
    clientConfig:
      service:
        name: validating-webhook-service
        namespace: default
        path: "/validate"
        port: 8443
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURyakNDQXBhZ0F3SUJBZ0lVYTRzczc0bVU4QXRHYlhBMzRFTjN1K2JxQWRFd0RRWUpLb1pJaHZjTkFRRUwKQlFBd01URXZNQzBHQTFVRUF3d21kbUZzYVdSaGRHbHVaeTEzWldKb2IyOXJMWE5sY25acFkyVXVaR1ZtWVhWcwpkQzV6ZG1Nd0hoY05NalV3TVRJM01UY3hOekk1V2hjTk1qWXdNVEkzTVRjeE56STVXakF4TVM4d0xRWURWUVFECkRDWjJZV3hwWkdGMGFXNW5MWGRsWW1odmIyc3RjMlZ5ZG1salpTNWtaV1poZFd4MExuTjJZekNDQVNJd0RRWUoKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBUGFRcjJldmUzb3ZkNStGS1dnUnovSGhBMys2dWFOdwpjS1NZWEtnOG9GWTFZcW9FZmovTUZhNG50RkpRVTJTcnJQREthSWNaNDhxTHRXdCs1UitHR0t5MU1JK0hQZGZNCk1yRUVCVkJaVXRudzZtK2tnNmt6QW5lTWFQcTVjWjU0cG5IVHpseVZXajc2dlZ4eHU0bXg2YzNxbDc2S1FwaDcKc09sYit6MUtKc0IrdklEV2MvbW4vSlNOSFk2bEQvZ3J1UXBaQnp1eFlUYStJOS83Qy9oVnJkUEEzdjF0YUlIQgpsSmlXeDVNdFIyMldRbGlUbktnMytPeVZ3T3NDODJBRUNUUDJVVkoya2lxaloyWXpJanRjWGVIbWNGU3dGakhmCkZZUUNBMUxXRDA5b25sdWtuU016YkthRWFZMnBvbGllZ2I5ZUMrQjZTMVJWT1MxWnhTZThNU2NDQXdFQUFhT0IKdlRDQnVqQWRCZ05WSFE0RUZnUVV6NGkzVEZTTlJ0OHptbkhaNURJRlc4SFB6YzB3SHdZRFZSMGpCQmd3Rm9BVQp6NGkzVEZTTlJ0OHptbkhaNURJRlc4SFB6YzB3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekJuQmdOVkhSRUVZREJlCmdpWjJZV3hwWkdGMGFXNW5MWGRsWW1odmIyc3RjMlZ5ZG1salpTNWtaV1poZFd4MExuTjJZNEkwZG1Gc2FXUmgKZEdsdVp5MTNaV0pvYjI5ckxYTmxjblpwWTJVdVpHVm1ZWFZzZEM1emRtTXVZMngxYzNSbGNpNXNiMk5oYkRBTgpCZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFNaTdoeE9VaTJXQ1c2c2hpVkVyQTBPRXM1bzdUWnlid25kaExHSGh5CnI4Y0N2UWF3ZHozejBLeThOVm8zVXV5TFhzVVRXaGxCMEd6STljZnNDbDRqbWpwTmVXcW5Hbk5aVldGNE1ET28KR2FwZy9ReStjVGF6ck9jSis3MEpyMVhzSXNheWRHYzZUa0hLNDhzV3BTTitoWW82UjR2cFJITWxFUHg2RVhyTApzNTJ4WEZOKzZjeXA4NlpBM2VDVVpRNW9TVnFidXh5ZE9uaDRvTktIeFdVVEZPZUFVd05RaTVXd0ZwR3dSVlBtCmQ4WlpYUExWUDRsVCtHS1VISy9MNjBpejVvQkk0dWlIazhzMTZRSDFMSytMZTgvTmZET2xURzFYc3NtNzY1WDEKam1DTi91OEhLMWZ4enJ1a0xKMFowQUVWdk5Hd0gyTHVPSDg3STBxTUxvQ09yZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
