apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-cert
  annotations:
    argocd.argoproj.io/sync-wave: "4"  # Deploy after pod is running
    cert-manager.io/inject-ca-from: default/validating-webhook-cert
webhooks:
  - name: validating-webhook-service.default.svc
    rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      operations: ["CREATE", "UPDATE"]
      resources: ["pods"]
      scope:       "Namespaced"
    failurePolicy: Fail
    sideEffects: None
    clientConfig:
      service:
        name: validating-webhook-service
        namespace: default
        path: "/validate"
        port: 8443
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
