apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-service
  annotations:
    argocd.argoproj.io/sync-wave: "7"  # Deploy after pod is running
    cert-manager.io/inject-ca-from: default/validating-webhook-cert
webhooks:
  - name: validating-webhook-service.default.svc
    rules:
    - apiGroups:
      - "*"
      apiVersions: ["v1"]
      operations: ["CREATE", "UPDATE"]
      resources: ["pods"]
      scope:       "*"
    failurePolicy: Fail
    sideEffects: None
    clientConfig:
      service:
        name: validating-webhook-service
        namespace: default
        path: "/validate"
        port: 443
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURyakNDQXBhZ0F3SUJBZ0lVWGRFOU9mY1R3RW40a3NrSURDa0FYaWdVUlpVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd01URXZNQzBHQTFVRUF3d21kbUZzYVdSaGRHbHVaeTEzWldKb2IyOXJMWE5sY25acFkyVXVaR1ZtWVhWcwpkQzV6ZG1Nd0hoY05NalV3TVRJM01UZ3pOREk0V2hjTk1qWXdNVEkzTVRnek5ESTRXakF4TVM4d0xRWURWUVFECkRDWjJZV3hwWkdGMGFXNW5MWGRsWW1odmIyc3RjMlZ5ZG1salpTNWtaV1poZFd4MExuTjJZekNDQVNJd0RRWUoKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTEZqZWZhL2p3aGs1TDZseDVLWmRYR2ZYSHRmNXlvcAovOXRmcE4wMVJ0ODcrdVZEdk1jeXdRWklTdXlhTEhYT1JEYjM3Vm9SVHVRa1ExT1htZ1dLNVc4L3pUVDFqQTltCncwc2kyS2wxWUtaczdxWFp2cTN5YzVJS2s2cmJvTG1vczF5ZGZFQTNLWU00YkRtOFNqRVpEVDVjelRkRzRSR0EKMUdvTml2MTJ4SUJHS1p6Wk41cmFuWGZxN0xrR05XU3NOY2RrbkptaDQ3K1VObzFnN0xxaGYySXB0RlU4d2M1eAp6V0tmNlFuT0Qva0FiMW1COUZwS0U5S2FzR3Y0Y2owbURHL09YaFNkZzdQay85YzROWXFndXZORWRYTVdYcGcrCnJ3MUlGQld1RzJEY0k2ejBKZk8wUTFSejI3MzM1KzdIL2phN3dwWFdWc0RieFRkMUpLUzE2c2tDQXdFQUFhT0IKdlRDQnVqQWRCZ05WSFE0RUZnUVVBL0NnY2UvVWdsQmVSdUdDRzFMby8vWi9EWUF3SHdZRFZSMGpCQmd3Rm9BVQpBL0NnY2UvVWdsQmVSdUdDRzFMby8vWi9EWUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekJuQmdOVkhSRUVZREJlCmdpWjJZV3hwWkdGMGFXNW5MWGRsWW1odmIyc3RjMlZ5ZG1salpTNWtaV1poZFd4MExuTjJZNEkwZG1Gc2FXUmgKZEdsdVp5MTNaV0pvYjI5ckxYTmxjblpwWTJVdVpHVm1ZWFZzZEM1emRtTXVZMngxYzNSbGNpNXNiMk5oYkRBTgpCZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFQY1Ayci90Wmp6QWhacHF5MGRGc3lkejRBTCtIUlZuVWZuT0x4bXY0CnVtVWJDZzJud2l4RWZIbzhVS0VDMk9NRTVYQUQzUklmOXBqSTd6bGdCdEN0L2xISDlWdjlqa3YrTHo5UExXY0oKMVZjOTVQckVSVnRFUWRqaDF0S0tkV2xCU3dQVjNKaXVvNk1wN0tpallmSUxKekQ4a1RsY1diT2txSktrZFJBUQo3R1M5dnZsVkdzT3crd0tPNC8rdFhhWEQyWnFQMk9CbjRyNDVNaXM1bm0zN01yNlEzN3N3Nm8yQ1JMam1BMXd5CkdqOWpZcnVOWjBBdWZrbmpOU2RiZUtXTHpHY0R3U1ovQW8xSVBKbHFhZUxwajVyZlZ4Si8wOUhqb1Nrb2JKRHgKUVZTaXUrS2c5RnFoT1AySktXcmptbGRUOWdNQWQ4dDE5Q3pJWVA4b0RPQk95UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
