apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pod-label-validation
webhooks:
  - name: pod-label-validator.default.svc
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
    failurePolicy: Fail
    sideEffects: None
    clientConfig:
      service:
        name: validating-webhook-service
        namespace: default
        path: "/validate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRekNDQWl1Z0F3SUJBZ0lVRlZTSUdtWE5PaVUxK25neGpwakNyRWpmNEpRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd01URXZNQzBHQTFVRUF3d21kbUZzYVdSaGRHbHVaeTEzWldKb2IyOXJMWE5sY25acFkyVXVaR1ZtWVhWcwpkQzV6ZG1Nd0hoY05NalV3TVRJM01URXpNREE0V2hjTk1qWXdNVEkzTVRFek1EQTRXakF4TVM4d0xRWURWUVFECkRDWjJZV3hwWkdGMGFXNW5MWGRsWW1odmIyc3RjMlZ5ZG1salpTNWtaV1poZFd4MExuTjJZekNDQVNJd0RRWUoKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBUHZUN3B5dVJNVklSQ0owbTB4ZzVNamRuUWs3NFNNYwpQRlEyR3Z6aXhxNjhLdjM1bWx3ZFhUempCcy9SRmhNUGlCUkxYK3VJZVBncmQrbnVVYytxNGNZLzdyZUV2NHUzCmg2bzkxSkowUE5RVlgvOG1tU1lHMG9XQWVFZzc0ZHJQRHFHMWJsZWEzenJMVW10RC9xMGwyMm5pVFBWQWREMWYKZWc3UFVjcGpwSDlHZWZqRVlwMmR1cmMvclZBUDdaaG93L09sd1dMRGdjMk80Y0lmOTdSTFlYSjJOdUR5Q0VhLwptKzBZK2tML2FMVGJnb1FWUkRpanBDb0xFaURVMDdOdUtMZWI1WWpvZ3NPYnVsdSs0cUV6azdNNE5TN0NFS0R6CkxZL0ZtVWRHSjRETmFWek5jZ3FXWUt0Q1pXSnFXL3NCTUs4Mkdlc1J2ZG1KQWZabnZpYmVqS3NDQXdFQUFhTlQKTUZFd0hRWURWUjBPQkJZRUZEZFY0VzU4WE9hMHJWV1g4bWp6dEQ5SWMvdVdNQjhHQTFVZEl3UVlNQmFBRkRkVgo0VzU4WE9hMHJWV1g4bWp6dEQ5SWMvdVdNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMCkJRQURnZ0VCQUhJaEYvdzU4LzJnMldyMDFkZ2pyUUpUejNzYm04c0VFbFFhejVaeVpDMDBPd1VhdkxLeGZIQzMKVHhDbHh3R2E1L0o0ZjdqVDZnR1NRYTV6QU1sVTV4S1FQbVVjaVZlRDNrMVI5TDd2NUZDWmdnS3IyV0dLSGwwTAo0dnEzUnlaaS9lRDkweXhLNmNKSERWWkY3WkFKSStRRUhPRHhZV1d3ZEpYK09MUWx2MDFkU25sWWFoUkh5YmxtClYxSGVXdUloZ3lnUndhdm5WbDZkRDF5WHpmRlBIR2lTTklhNjJ0RHVzVy9PWmRmUDMrc3QvbVB4dHJ0VFRTQm0KdGVIVFVGd0VCNlNWSHM3Y1NYME1ocjZLeFFFck9adllzRDlhczgyL0RSTFBHRUwzU0YyRFhTNXZYSjQ0ZDFUdApUVFNaeDlnZU1vcmNnZXZKR2Y2cnBaaDNFZjVGeGNNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
